markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: "/origin"

version: 2.3.3

sass:
  # Directory points to root to allow the `@import` of .scss files from anywhere
  sass_dir: assets/scss
  style: compressed

github:
  repo: https://github.com/fac/origin
